name: Deploy

on:
  push:
    branches:
      - main

env:
  MONGOURI: ${{ secrets.MONGOURI }}
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Depedencies
        run: npm install

      - name: Run the tests
        run: |
          cd frontend
          npm install
          npm test search

      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Deploy
        run: |
          heroku git:remote -a cise-ass1b-group6
      -  uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'cise-ass1b-group6'
          heroku_email: 'cindychen042@gmail.com'

